#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import time

"""Advent of Code 2022
   Day 2
   Red-Nosed Reports
"""

def measure_time(func, *args, **kwargs):
    start_time = time.time()
    result = func(*args, **kwargs)
    elapsed_time = time.time() - start_time
    return result, elapsed_time

def main():
    print("Advent of Code 2024 - Day 2")
    with open("input.txt") as file:
        reports = [list(map(int, line.split())) for line in file.readlines()]

    saved_reports, time_taken = measure_time(count_reports_safes, reports)
    print(f"Part 1: {saved_reports} Reports Safe (Time: {time_taken:.8f} seconds)")

    saved_reports, time_taken = measure_time(count_reports, reports)
    print(f"Part 2: {saved_reports} Reports Safe (Time: {time_taken:.4f} seconds)")


def verify_report(report: list) -> bool:
    is_increasing = None
    for i in range(len(report)-1):
        level = report[i+ 1] - report[i]
        if level > 0:
            if is_increasing is None:
                is_increasing = True
            elif is_increasing is False:
                return False
        elif level < 0:
            if is_increasing is None:
                is_increasing = False
            if is_increasing:
                return False
        if not (1 <= abs(level) <= 3):
            return False
    return True

def count_reports_safes(reports: list) -> int:
    count = 0
    for report in reports:
        if verify_report(report):
            count += 1
    return count

def report_safe(report: list) -> list:
    subsets = [report[:i] + report[i + 1:] for i in range(len(report))]
    for subset in subsets:
        if verify_report(subset):
            return subset

def count_reports(reports: list) -> int:
    count = 0
    for report in reports:
        if verify_report(report):
            count += 1
        else:
            unsafe = report_safe(report)
            if unsafe and verify_report(unsafe):
                count += 1
    return count

if __name__ == "__main__":
    main()

