#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Advent of Code 2022
    Day 2
   Calorie Counting
"""

import heapq
f = open("dataday.txt", "r")
s = int(0)
elf = []
for x in f:
    if x in ['\n', '\r\n']:
       elf.append(s)
       s = 0
    else:
        s = s + int(x)
m = heapq.nlargest(3,elf)
print("Amounts of Calories of the heaviest elf: " + str(m[0]))
print("Sum of the calories of the three heaviest elves: {}".format(sum(m)))
