#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import time

"""Advent of Code 2024
   Day 5
   Print Queue
"""

def main():
    print('Advent of Code 2024 - Day 5: Print Queue')
    rules, pages = read_file('input.txt')

    start_time = time.time()
    result = sum_middle_correct_pages(pages, rules)
    end_time = time.time()
    print(f'Part 1: {result} (Time: {end_time - start_time:.4f} seconds)')
    start_time = time.time()
    result = sum_middle_incorrect_pages(pages, rules)
    end_time = time.time()
    print(f'Part 2: {result} (Time: {end_time - start_time:.4f} seconds)')

def read_file(filename):
    with open(filename) as f:
        lines = f.readlines()

    rules = extract_rules(lines)
    pages = extract_pages(lines)

    return rules, pages

def extract_rules(lines):
    rules = []
    for line in lines:
        if '|' in line:
            rules.append([int(x) for x in line.strip().split('|')])
    return rules

def extract_pages(lines):
    pages = []
    for line in lines:
        if ',' in line:
            pages.append([int(x) for x in line.strip().split(',')])
    return pages

def check_order(page, rules):
    for rule in rules:
        if len(rule) != 2:
            continue
        first, second = rule
        if first in page and second in page:
            idx_first = page.index(first)
            idx_second = page.index(second)
            if idx_first > idx_second:
                return False
    return True

def find_incorrect_pages(pages, rules):
    incorrect_pages = []
    for page in pages:
        if not check_order(page, rules): incorrect_pages.append(page)
    return incorrect_pages

def pages_ordering(pages, rules):
    for page_index, page in enumerate(pages):
        for i in range(len(page)):
            for j in range(i + 1, len(page)):
                for rule in rules:
                    if {page[i], page[j]} == set(rule):
                        if rule.index(page[i]) > rule.index(page[j]):
                            pages[page_index][i], pages[page_index][j] = page[j], page[i]
    return pages

def sum_middle_correct_pages(pages, rules):
    total = 0
    for page in pages:
        if check_order(page, rules):
            middle_index = len(page) // 2
            total += page[middle_index]
    return total

def sum_middle_incorrect_pages(pages, rules):
    pages = find_incorrect_pages(pages, rules)
    pages = pages_ordering(pages, rules)
    total = 0
    for page in pages:
        middle_index = len(page) // 2
        total += page[middle_index]
    return total

if __name__ == '__main__':
    main()
