#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Advent of Code 2025
    Day 1
    Secret Entrance
	Part 1
"""

def left(dial, n):
    global password
    while n > 0:
        dial -= 1
        n -= 1
        if dial == -1:
            dial = 99
    if dial == 0:
        password+=1
    return dial

def right(dial, n):
    global password
    while n > 0:
        dial += 1
        n -= 1
        if dial == 100:
            dial = 0
    if dial == 0:
        password+=1
    return dial

def rotation(instruction):
    global dial
    p = instruction[0]
    num = int(instruction[1:])
    if p == 'L':
        dial = left(dial, num)
    elif p == 'R':
        dial = right(dial, num)

dial = 50
password = 0 
f = open('input.txt', 'r').read().splitlines()
for instruction in f:
    rotation(instruction)
print(password)
