#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Advent of Code 2024
   Day 1
   Historian Hysteria
"""

def part1():
    # f = open('example.txt', 'r').read().splitlines()
    f = open('input.txt', 'r').read().splitlines()

    smaller_left=[]
    smaller_right=[]

    total_distance=0

    for line in f:
        l=line.split()
        smaller_left.append(int(l[0]))
        smaller_right.append(int(l[1]))

    smaller_left.sort()
    smaller_right.sort()

    for i,j in zip(smaller_left, smaller_right):
        distance = j-i
        if(distance>0):
            total_distance+=distance
        if(distance<0):
            total_distance+=(distance*-1)

    print(f"Part One: {total_distance}")

def part2():
    # f = open('example.txt', 'r').read().splitlines()
    f = open('input.txt', 'r').read().splitlines()
    
    similarity_score = 0
    left=[]
    right=[]

    for line in f:
        l=line.split()
        left.append(int(l[0]))
        right.append(int(l[1]))

    for i in left:
        frequency=0
        for j in right:
            if i==j:
                frequency+=1
        similarity_score+=(i*frequency)
    print(f"Part Two: {similarity_score}")

if __name__ == "__main__":
    print("Advent of Code 2024 - Day One")
    part1()
    part2()
